import { db } from '@/db';
import { stories } from '@/db/schema';

async function main() {
    const sampleStories = [
        {
            title: 'City Council Approves $50M Infrastructure Upgrade for Downtown Core',
            slug: 'city-council-approves-50m-infrastructure-upgrade-downtown-core',
            excerpt: 'The municipal council unanimously voted to approve a comprehensive infrastructure overhaul targeting aging water systems and road repairs. The multi-year project will begin in spring 2024 and aims to modernize critical urban infrastructure.',
            content: 'In a landmark decision yesterday evening, the city council approved a $50 million infrastructure upgrade package that will transform the downtown core over the next three years. The comprehensive plan addresses decades of deferred maintenance on water systems, road surfaces, and underground utilities that have plagued the area.\n\nMayor Sarah Thompson emphasized the urgency of the project, stating that recent engineering assessments revealed critical weaknesses in the current infrastructure. "We cannot afford to wait any longer," Thompson said during the council meeting. "This investment will ensure our downtown remains vibrant and safe for residents and businesses alike."\n\nThe project will be funded through a combination of municipal bonds, provincial grants, and federal infrastructure programs. Construction is expected to begin in April 2024, with the first phase focusing on the main commercial district along King Street.\n\nLocal business owners have expressed mixed reactions, with some concerned about potential disruptions during construction while others welcome the long-overdue improvements. The city has committed to working closely with affected businesses to minimize economic impact during the renovation period.',
            categoryId: 1,
            author: 'Michael Chen',
            image: 'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=800&h=600&fit=crop',
            featured: true,
            publishedAt: new Date('2024-12-15').toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: 'New Affordable Housing Initiative Launches in East District',
            slug: 'new-affordable-housing-initiative-launches-east-district',
            excerpt: 'The city announces a groundbreaking affordable housing program targeting young families and seniors. Construction on the first 200 units will begin early next year with rent controls guaranteed for 15 years.',
            content: 'The municipal housing authority unveiled an ambitious affordable housing initiative that will create 500 new units in the East District over the next four years. The $75 million project specifically targets young families earning between $40,000 and $70,000 annually, as well as seniors on fixed incomes.\n\nHousing Director Jennifer Martinez explained that the program addresses the city\'s most pressing housing shortage. "We\'ve seen a 40% increase in housing costs over the past five years, pricing out essential workers like teachers, healthcare workers, and municipal employees," Martinez noted during the announcement.\n\nThe development will feature a mix of one, two, and three-bedroom units, with 30% reserved for seniors and 70% for families. Rent will be capped at 30% of median area income, with built-in protections against speculation and rapid rent increases.\n\nConstruction partners include local union contractors and sustainable building specialists, ensuring the project meets both employment and environmental standards. The first residents are expected to move in by fall 2025.',
            categoryId: 1,
            author: 'Lisa Rodriguez',
            image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&h=600&fit=crop',
            featured: false,
            publishedAt: new Date('2024-12-12').toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: 'Provincial Budget Allocates Record $2.3B for Healthcare System Improvements',
            slug: 'provincial-budget-allocates-record-23b-healthcare-system-improvements',
            excerpt: 'The provincial government announces unprecedented healthcare funding to address staffing shortages and infrastructure needs. The investment includes new medical schools and expanded nurse training programs.',
            content: 'Premier David Williams delivered the provincial budget yesterday, highlighting a record-breaking $2.3 billion investment in healthcare infrastructure and human resources. The comprehensive package addresses critical staffing shortages that have plagued hospitals and clinics across the province for the past three years.\n\nThe funding will establish two new medical schools in underserved regions and expand nursing programs at existing institutions by 50%. Additionally, $800 million is earmarked for hospital equipment upgrades and the construction of three new regional medical centers.\n\nHealth Minister Dr. Patricia Kim emphasized the urgency of the investment, citing recent data showing nurse vacancy rates at 12% and physician shortages in rural areas exceeding 25%. "This budget represents our commitment to ensuring every resident has access to quality healthcare when they need it most," Dr. Kim stated.\n\nThe opposition has cautiously welcomed the announcement while questioning implementation timelines. Healthcare unions have praised the funding but stress that systemic changes in working conditions must accompany the financial investment to retain existing staff.',
            categoryId: 2,
            author: 'Robert Thompson',
            image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1f?w=800&h=600&fit=crop',
            featured: true,
            publishedAt: new Date('2024-12-10').toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: 'Education Reform Package Introduces New Digital Literacy Requirements',
            slug: 'education-reform-package-introduces-new-digital-literacy-requirements',
            excerpt: 'Starting September 2024, all high school students will be required to complete digital literacy courses. The province invests $400M in technology infrastructure and teacher training to support the initiative.',
            content: 'Education Minister Janet Foster announced sweeping curriculum changes that will make digital literacy a graduation requirement for all high school students beginning in September 2024. The reform package includes $400 million in funding for technology infrastructure and comprehensive teacher training programs.\n\nThe new requirements will cover coding fundamentals, digital citizenship, cybersecurity awareness, and data analysis skills. Students will need to complete a minimum of 120 hours of digital literacy coursework spread across their four years of high school.\n\n"In today\'s economy, digital skills are as fundamental as traditional literacy and numeracy," Minister Foster explained during the legislative announcement. "This initiative ensures our graduates are prepared for the jobs of tomorrow, whether in technology, healthcare, manufacturing, or service industries."\n\nThe program will begin with a pilot in 50 schools this spring, with full province-wide implementation by fall 2024. Teachers will receive intensive summer training, and schools will be equipped with updated computer labs and high-speed internet infrastructure where needed.',
            categoryId: 2,
            author: 'Amanda Parker',
            image: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800&h=600&fit=crop',
            featured: false,
            publishedAt: new Date('2024-12-08').toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: 'Transit Authority Under Investigation for $15M Contract Irregularities',
            slug: 'transit-authority-under-investigation-15m-contract-irregularities',
            excerpt: 'Provincial auditors discover significant discrepancies in transit infrastructure contracts awarded over the past two years. Three senior officials have been suspended pending investigation results.',
            content: 'The Provincial Transit Authority is facing intense scrutiny following the discovery of irregular contracting practices totaling $15 million in questionable expenditures. The provincial auditor\'s office launched the investigation after anonymous whistleblower complaints raised concerns about bid manipulation and undisclosed conflicts of interest.\n\nAuditor General Margaret Stevens confirmed that three senior transit officials have been suspended with pay while investigators examine contracts awarded between 2022 and 2024. The probe focuses on bus procurement contracts, station renovation projects, and consulting services that appear to have bypassed standard competitive bidding processes.\n\n"Our preliminary findings suggest a pattern of favoritism in contract awards, with some vendors receiving multiple lucrative contracts despite not submitting the lowest bids," Stevens reported to the legislative committee. The investigation has uncovered email communications suggesting coordination between officials and preferred contractors.\n\nTransit Authority CEO David Morrison has denied any wrongdoing but acknowledged "procedural gaps" in oversight systems. The scandal threatens to delay several major transit expansion projects as all current contracts undergo review.',
            categoryId: 3,
            author: 'Sarah Mitchell',
            image: 'https://images.unsplash.com/photo-1544427920-c49ccfb85579?w=800&h=600&fit=crop',
            featured: false,
            publishedAt: new Date('2024-12-14').toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: 'Former Municipal Planning Director Charged in Zoning Bribery Scheme',
            slug: 'former-municipal-planning-director-charged-zoning-bribery-scheme',
            excerpt: 'Police arrest former planning director Thomas Blake on charges of accepting bribes from developers. The investigation reveals a systematic scheme spanning four years and involving multiple high-profile projects.',
            content: 'Former Municipal Planning Director Thomas Blake was arrested yesterday on charges of accepting bribes from real estate developers in exchange for favorable zoning decisions. The charges stem from a two-year investigation by the provincial anti-corruption unit that uncovered systematic abuse of the planning approval process.\n\nBlake, who served as planning director from 2018 to 2023, allegedly received over $300,000 in cash payments, luxury vacations, and home renovations from developers seeking approval for controversial projects. Court documents reveal that Blake expedited approvals for projects that should have undergone extensive environmental and community impact reviews.\n\nThe investigation began when community groups complained about suspiciously rapid approvals for a controversial waterfront development. Detective Inspector Karen Walsh confirmed that the probe has expanded to examine at least twelve major development projects approved during Blake\'s tenure.\n\nMayor Thompson expressed shock at the allegations and announced an immediate review of all planning decisions made in the past five years. "The public trust has been violated, and we will take every step necessary to restore confidence in our municipal planning process," Thompson stated.',
            categoryId: 3,
            author: 'James Wilson',
            image: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&h=600&fit=crop',
            featured: false,
            publishedAt: new Date('2024-12-11').toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: 'Healthcare Procurement Scandal Widens as More Hospitals Implicated',
            slug: 'healthcare-procurement-scandal-widens-more-hospitals-implicated',
            excerpt: 'Investigation into inflated medical supply contracts expands to include five regional hospitals. Preliminary findings suggest coordinated bid-rigging resulted in $8M in excessive costs over three years.',
            content: 'The healthcare procurement scandal that began with allegations against Central Regional Hospital has expanded to encompass five medical facilities across the province. Investigators now believe a coordinated bid-rigging scheme resulted in $8 million in excessive costs for medical supplies and equipment over a three-year period.\n\nProvincial Health Investigator Maria Santos confirmed that the scheme involved collusion between hospital purchasing managers and medical supply companies to inflate contract prices. "We\'ve identified a pattern of identical bid submissions and suspicious timing in contract awards that suggests systematic coordination," Santos reported.\n\nThe investigation has revealed that participating hospitals paid 20-40% above market rates for common medical supplies including surgical equipment, diagnostic tools, and basic medications. Three hospital administrators have been suspended, and two medical supply companies have had their provincial contracts terminated.\n\nHealth Minister Dr. Kim announced immediate reforms to centralize procurement processes and implement stronger oversight mechanisms. "This breach of public trust is unacceptable, and we will ensure taxpayer funds are protected through enhanced transparency and accountability measures," Dr. Kim stated during an emergency press conference.',
            categoryId: 3,
            author: 'Catherine Lee',
            image: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=800&h=600&fit=crop',
            featured: true,
            publishedAt: new Date('2024-12-13').toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: 'Why Our City Needs Bold Action on Climate Resilience Now',
            slug: 'why-our-city-needs-bold-action-climate-resilience-now',
            excerpt: 'Recent flooding events demonstrate our infrastructure\'s vulnerability to extreme weather. Local government must prioritize climate adaptation investments before the next major storm hits our community.',
            content: 'The recent flooding that devastated three neighborhoods in our city serves as a stark reminder that climate change is not a distant threat—it\'s happening right here, right now. The storms that overwhelmed our drainage systems and forced dozens of families from their homes should be a wake-up call for municipal leaders who have been slow to embrace climate resilience planning.\n\nFor too long, our city has approached infrastructure with a "fix it when it breaks" mentality that ignores the increasing frequency and intensity of extreme weather events. The outdated storm water management systems installed in the 1970s were never designed to handle the precipitation levels we\'re now experiencing regularly.\n\nThe solution requires more than emergency repairs and temporary flood barriers. We need comprehensive climate adaptation strategies that include green infrastructure, upgraded drainage systems, and flood-resistant building codes. Cities across North America have successfully implemented such measures, proving that proactive investment prevents costly disaster recovery.\n\nThe upcoming municipal budget presents an opportunity to prioritize long-term resilience over short-term savings. Council members must recognize that the cost of inaction far exceeds the investment required to protect our community from future climate impacts.',
            categoryId: 4,
            author: 'Dr. Emily Watson',
            image: 'https://images.unsplash.com/photo-1611273426858-450d8e3c9fce?w=800&h=600&fit=crop',
            featured: false,
            publishedAt: new Date('2024-12-09').toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: 'The Housing Crisis Demands Regional Solutions, Not Band-Aid Policies',
            slug: 'housing-crisis-demands-regional-solutions-not-band-aid-policies',
            excerpt: 'Municipal and provincial governments must coordinate comprehensive housing strategies. Piecemeal approaches and short-term thinking have failed to address the root causes of our affordability crisis.',
            content: 'The announcement of yet another small-scale affordable housing project highlights the fundamental disconnect between the scale of our housing crisis and the inadequacy of current policy responses. While 200 new affordable units represent progress, they barely address the tip of an iceberg that threatens to sink our region\'s economic future.\n\nOur housing shortage didn\'t emerge overnight, and it won\'t be solved by scattered developments and feel-good announcements. The crisis stems from decades of poor planning, restrictive zoning policies, and a failure to coordinate housing strategy across municipal boundaries. Workers can\'t afford to live where they work, forcing longer commutes that strain transportation systems and harm environmental goals.\n\nSuccessful housing policies require regional thinking and sustained political commitment. We need coordinated zoning reform, inclusive development requirements, and long-term funding mechanisms that can scale to meet actual demand. Countries like Austria and Singapore have demonstrated that government-led housing programs can provide quality, affordable homes at scale.\n\nThe current approach of celebrating small victories while ignoring systemic failures does a disservice to the thousands of families struggling with unaffordable housing costs. Our leaders must embrace bold, comprehensive solutions that match the magnitude of the challenge.',
            categoryId: 4,
            author: 'Mark Davidson',
            image: 'https://images.unsplash.com/photo-1582407947304-fd86f028f716?w=800&h=600&fit=crop',
            featured: false,
            publishedAt: new Date('2024-12-07').toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: 'New Trade Agreement with European Union Boosts Local Manufacturing',
            slug: 'new-trade-agreement-european-union-boosts-local-manufacturing',
            excerpt: 'Federal trade deal eliminates tariffs on specialized manufacturing equipment and components. Local factories expect increased export opportunities and job growth in advanced manufacturing sectors.',
            content: 'The federal government\'s new comprehensive trade agreement with the European Union promises significant benefits for local manufacturing companies, particularly those specializing in advanced materials and precision engineering. The deal eliminates tariffs on over 300 categories of industrial equipment and components, reducing costs for local manufacturers while opening new export markets.\n\nRegional Manufacturing Council President Sandra Liu estimates that local companies could see export opportunities increase by 35% over the next three years. "This agreement levels the playing field with our international competitors and recognizes the high quality of Canadian manufacturing," Liu stated during a press conference with federal trade officials.\n\nThe agreement specifically benefits the region\'s aerospace suppliers, automotive parts manufacturers, and renewable energy equipment producers. Companies like Precision Components Inc. and Advanced Materials Solutions have already announced expansion plans, anticipating increased demand from European customers.\n\nEconomic Development Agency projections suggest the trade deal could create 800 new manufacturing jobs in the region over the next five years. The agreement also includes provisions for technology transfer and joint research initiatives between Canadian and European companies, potentially attracting additional investment in research and development facilities.',
            categoryId: 5,
            author: 'Daniel Kim',
            image: 'https://images.unsplash.com/photo-1565650287563-7280dbc86843?w=800&h=600&fit=crop',
            featured: false,
            publishedAt: new Date('2024-12-06').toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: 'Global Supply Chain Disruptions Impact Local Port Operations',
            slug: 'global-supply-chain-disruptions-impact-local-port-operations',
            excerpt: 'Recent shipping delays in Asia affect cargo schedules at regional port facilities. Local businesses prepare for potential product shortages during peak holiday season.',
            content: 'Ongoing shipping delays in major Asian ports are creating ripple effects for the regional shipping terminal, with cargo backlogs threatening to impact local businesses during the crucial holiday retail season. Port Authority Director Rachel Martinez reports that container arrivals are running 8-12 days behind schedule due to labor disputes and weather-related closures in Shanghai and Hong Kong.\n\nThe delays affect a wide range of imported goods, from electronics and clothing to automotive parts and seasonal merchandise. Local retailers are expressing concern about potential stock shortages during their busiest sales period, with some already implementing inventory rationing measures.\n\n"We\'re seeing the same supply chain vulnerabilities that affected us during the pandemic," explained Import/Export Association President Tom Chen. "The interconnected nature of global shipping means disruptions thousands of miles away directly impact our local economy."\n\nPort officials are working with shipping companies to prioritize time-sensitive cargo and explore alternative routing options through West Coast ports. However, these solutions come with additional costs that may be passed on to consumers. Local businesses are advised to communicate proactively with customers about potential delays and to diversify their supplier networks to reduce future vulnerability.',
            categoryId: 5,
            author: 'Jennifer Zhang',
            image: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&h=600&fit=crop',
            featured: false,
            publishedAt: new Date('2024-12-05').toISOString(),
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        }
    ];

    await db.insert(stories).values(sampleStories);
    
    console.log('✅ Stories seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});